steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest']

images:
  - 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging instead of GCS
