
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest', '.']
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest']

# Optional: Define images to be built and pushed
images:
  - 'asia-south1-docker.pkg.dev/payapt-demo/payapt-frontend:latest'
